### ISSUE TITLE
Unexpected error on iPad after another player finish their turn

### ISSUE THREAD

**Issue by earlyshen** [ymichael/everdell#17]
**Describe the bug**
Player on iPad with mobile Safari need to manual refresh every time after another player finishes her/his turn. 
Discovered this on a two player game.

**To Reproduce**

1. Player 1(iPad) place a worker on any basic location
2. Player 2(Mac) page refreshed
3. Player 2(Mac) place a worker on any basic location
4. Player 1(iPad) see an error as shown in screenshot

Depending on the issue, other things that may be relevant:

- Player 1(iPad) could manual refresh the page when seeing the error as workaround. It functions normally after a manual refresh.

**Expected behavior**
Player 1 on iPad should see a refreshed page without error message.

**Screenshots**
![IMG_0115](https://user-images.githubusercontent.com/1399753/105085021-043c3100-5a4c-11eb-97a8-2591374bb84a.PNG)

**Browser / Device Info (if relevant):**

Player 1: Safari on iPad Pro (11 inch) with iPadOS 14.3
Player 2: Microsoft Edge Version 87.0.664.41 (Official build) (64-bit) on macOS 10.15.7 (19H114)

**Comment by earlyshen** [comment]
Thank you guys for making this game available online. This is awesome! The bug I reported here is a very minor one as it has an easy workaround. Overall the experience is pretty good so far. Great job!

**Comment by ymichael** [comment]
Thanks for reporting the bug. It should be fixed now :)

**Comment by earlyshen** [comment]
I could verify that this get fixed. Thank you so much 😃
