### ISSUE TITLE
Could not claim basic event tile near end game

### ISSUE THREAD

**Issue by earlyshen** [ymichael/everdell#18]
**Describe the bug**
Could not claim basic event tile

**To Reproduce**
Not sure this could be reproduced every time. Here is our full game play:
http://everdell.herokuapp.com/game/pw5aRV6qMztNT6KJmPqv1u?playerSecret=36aH9t8uFwqcGUGpeYp3Tz

The bug shows up right before end game. Player M has ended all seasons. E still has couple moves:

```
>> M took the game end action.
>> E played Monk.
>> Monk: E gave 2 berries to M to gain 4 coins.

// E should be able to claim the production basic event here but an error shows up.
// E has no choice but placing his last worker in a random location to end this game.

>> E place a worker on resin&card.
>> E took the game end action.
>> Game over
>> M has 63 points.
>> E has 53 points.
```

When Player E is trying to claim that production event, an error message popped up: `Need to specify clientOptions.event`. See the screenshot below. 

The city could be found in the link. E does have 7 green production at that time, which is more than enough to claim that event. 

**Expected behavior**
Player should be able to claim basic event tile when the requirement is met.

**Screenshots**
![IMG_0117](https://user-images.githubusercontent.com/1399753/105132199-56f30880-5a9f-11eb-9f71-6c2e45aba48f.PNG)

**Browser / Device Info (if relevant):**
Safari on iPad Pro 11 inch with iPadOS 14.3

**Comment by ymichael** [comment]
Thanks for the report, I believe this error happens if you don't click on the event to select it before submitting. So the game thinks that you've not selected any event to claim!

I think the UI is not very clear and the error message can be more helpful. We could probably also auto select the event if there just one to be claimed.

**Comment by ymichael** [comment]
The game log in your screenshot also looks really broken and unreadable 😔 (we should fix that as well)

**Comment by earlyshen** [comment]
Thanks for the quick response. Ah 🤦🏻‍♂️ you are right I might have forgot to select that event. Yeah some rewording on that popup message will be super helpful.

**Comment by earlyshen** [comment]
For the log message it is still readable on iPad, but yeah if the line spacing could be fixed that will be awesome.
