### ISSUE TITLE
Show total number of critter/construction on the card

### ISSUE THREAD

**Issue by earlyshen** [ymichael/everdell#21]
**What's your idea / feature request?**
There is a tiny detail (mark on the trunk) on the physical card that is super useful especially when playing some rare critter/construction. It will be awesome to have this information in digital version.
![26cebabc24fcd670a80e06b6c6969796](https://user-images.githubusercontent.com/1399753/105521700-16f37780-5c91-11eb-92b8-5b3e2ee79ae3.png)

**Describe the solution you'd like**
Not a good designer but something like this might work well
![Screen Shot 2021-01-22 at 9 16 13 AM](https://user-images.githubusercontent.com/1399753/105522953-b5cca380-5c92-11eb-9748-8979396e0f37.png)

**Comment by ymichael** [comment]
Thanks for the suggestion, Added this: http://everdell.herokuapp.com/test/ui

**Comment by earlyshen** [comment]
Thank you for adding this. So efficient, I am so impressed! 🎉
