### ISSUE TITLE
Miner Mole Mislabeling

### ISSUE THREAD

**Issue by dwaynedauzat** [ymichael/everdell#22]
When using the Miner Mole, the text said I was choosing a card to copy from the "Meadow" instead of from the "Card Owner."  See screenshot areas circled in red.  It worked correctly it just said the wrong thing in the text.

![Everdell Miner Mole Mistake](https://user-images.githubusercontent.com/70274065/105563554-133d1080-5ce4-11eb-959e-bd5d97657da9.jpg)

**Comment by ymichael** [comment]
Thanks for the report! We'll fix this!
