### ISSUE TITLE
Miner Mole should become the copied card in opponent's city

### ISSUE THREAD

**Issue by earlyshen** [ymichael/everdell#23]
**Describe the bug**
According to the rulebook. `Miner Mole` should become the copied card in opponent's city. If the copied effect requires any other card in the city, it should check the opponent's city not the city where `Miner Mole` is in.

![IMG_0119](https://user-images.githubusercontent.com/1399753/105648658-799b6d80-5e61-11eb-9ae2-3628c04548e0.jpg)
 

**To Reproduce**
1. A has `Farm` & `Barge Toad` in his city
2. B doesn't have a `Farm` in town. B plays `Miner Mole` and specify `Barge Toad` in A's city
3. B gains no twigs

**Expected behavior**
B should gain 2 twigs because there is a `Farm` in A's city

**Comment by ymichael** [comment]
Thanks for catching this! Pushed a fix, will deploy this shortly
