### ISSUE TITLE
Fool is not playable by Cemetary to opponents' city when there is one in town

### ISSUE THREAD

**Issue by earlyshen** [ymichael/everdell#25]
**To Reproduce**

This is a 4 player game
1. A has a `Fool` (played by other player) in his city. All players' cities are not fulled. 
2. A places a worker on `Cemetary`. Reveals 4 cards from discarded pile: `Chapel`, `Fool`, `Monk`, `Postal Pigeon`
3. A could only select `Chapel`, `Monk`, `Postal Pigeon` but not `Fool`

This is probably because `Fool` card is an unique critter so the system think it is not playable. However, `Fool` card is supposed to be played to an opponent's city.

**Expected behavior**
A should be able to select `Fool` and play it to opponent's city.

**Screenshots**
![IMG_0120](https://user-images.githubusercontent.com/1399753/105652688-bfaafe00-5e6e-11eb-9fe8-ef9994845a38.PNG)

**Comment by ymichael** [comment]
Great find, will fix

**Comment by elynnlee** [comment]
+1, this is a really great find!! Thanks for reporting this!!
