### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by elynnlee** [ymichael/everdell#31]
**What's your idea / feature request?**
It would be great if there was an undo button, in the event that you choose the wrong option / card

**Comment by FlashPapa** [comment]
This is a good idea, but the problem is that for some game turn you have to draw cards so you have to find the next cards from the draw pile.
So if we cancel our action, we could see the next draw cards and play something else which would be cheating
What do you think ?

**Comment by ymichael** [comment]
This is now an option that you can pick when creating a new game! For the drawing cards case, this is currently based on an honor system if you have this option enabled, if you undo after drawing a card, the deck just resets to the previous state (the drawn cards are added back to the deck)
