### ISSUE TITLE
BUG: Cannot resolve production buildings at the end of summer and finish game

### ISSUE THREAD

**Issue by mloballer** [ymichael/everdell#40]
Thanks a lot for creating this app, I and my friends have been enjoying it very much.

In our game there seems to be a bug, my friend cannot proceed. He is just stuck on activating his production buildings to go into autumn. When using the peddler, it won't let him select his resources. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/10591526/113470629-f1f74f80-940b-11eb-9eb6-6dbc8b15ce74.png)

The game spectator id is: https://everdell.vercel.app/game/9GVYqkviwhYBSXoaYeXafp

Is there any way you can give him a wood and a resin, or flag something so it will let him choose his resources and we can continue the game? thanks!!

**Comment by ymichael** [comment]
Sorry about that! I found the issue here and this should be fixed shortly once the fix deploys

**Comment by ymichael** [comment]
This should be fixed now!
