### ISSUE TITLE
Deck count

### ISSUE THREAD

**Issue by mloballer** [ymichael/everdell#44]
I was wondering would it be possible to get a count of how many cards are in the current deck before it runs out and gets reshuffled? Kind of useful to know where the current deck is at if you are fishing for a specific card, thanks.

**Comment by ymichael** [comment]
Thanks for the feature request! We've been meaning to add this too!

<img width="843" alt="Screen Shot 2021-05-26 at 7 42 23 PM" src="https://user-images.githubusercontent.com/610102/119757985-9de07880-be5a-11eb-9a3f-cc11552b0820.png">
