### ISSUE TITLE
WOODCARVER, CHAPEL Event

### ISSUE THREAD

**Issue by mloballer** [ymichael/everdell#46]
I noticed the text for this event says:

![image](https://user-images.githubusercontent.com/10591526/120012675-a937bf00-bf94-11eb-89bb-026f499f3e11.png)

I am still new to the game, and I thought that is the worst event in the game. Then I looked up the official card:

![image](https://user-images.githubusercontent.com/10591526/120012792-d2f0e600-bf94-11eb-999c-d44718a47103.png)

I am assuming the programming is correct and that it gives you the two points for each point token on your chapel? Seems to be missing the event description, thanks!

**Comment by elynnlee** [comment]
Thanks for reporting this! Fix is live and I'll take a look at the other events to make sure they aren't missing any game text :)
