### ISSUE TITLE
Cemetery card not working as intended with choosing discard pile

### ISSUE THREAD

**Issue by mloballer** [ymichael/everdell#52]
**Describe the bug**
The cemetary is not working as intended, it should pull the top 4 cards from the discard pile, but seems to be pulling from the bottom

**To Reproduce**
Just use the cemetery (we had 10 cards in the discard pile when we activated it)

**Expected behavior**
Should have revealed the top 4 cards in the discard pile

**Screenshots**
Here is the game link if you want to see the log, as you can see when the cemetery was used it pulled up cards that were discarded way before:

https://everdell.vercel.app/game/u675mm2oiNz63rR3dr7P74

**Browser / Device Info (if relevant):**
Chrome

**Additional context**
N/A

**Comment by ymichael** [comment]
Fixed by d46f8cfa6cf1b4845badc632cb9af5fe2adb2b21
