### ISSUE TITLE
Open destinations should indicate that the owner will gain a victory point on opponent worker visiting it

### ISSUE THREAD

**Issue by erikhuizinga** [ymichael/everdell#54]
**What's your idea / feature request?**

Show that open locations will have the owner gain a victory point.

**Is your feature request related to a problem or pain point?**

Open locations like the Inn can be visited by opponent workers. The location owner gains 1 victory point when that happens. The UI doesn't show this. Only after selecting to visit the location the game log shows that the owner gained 1 point.

**Describe the solution you'd like**

The open card already shows that the destination is available to opponent workers. The text should also say that the card owner will gain a point when an opponent visits the destination.

**Additional context**

Related to #2 but that was closed.

**Comment by elynnlee** [comment]
Thanks for reporting / filing the feedback!!
