### ISSUE TITLE
Judge not activating

### ISSUE THREAD

**Issue by hannahcin** [ymichael/everdell#55]
Hi there,
In a 4-player game we just played, 2 players both had the Judge played in their city, but neither ever was given the option to activate the Judge when playing a card. They played many cards where the Judge was the only blue card in their city, and still were never given the option to swap a resource. This occurred both when playing cards from their hand or the meadow.

**To Reproduce**

1. Play a Judge
2. Play any card from the meadow
3. See there is no option to swap a resource
4. Play any card from your hand
5. See there is no option to swap a resource

**Expected behavior**

After playing any card from the meadow or hand, a player with a Judge in their city should be given the option to swap 1 resource.

**Comment by elynnlee** [comment]
Hi @hannahcin and friends!! Thanks for reporting this :)

Just checking -- when you have a Judge in your city, the game will automatically account for this when you choose resources to pay with! Here's an example:

Here you can see the resources I have + which cards I can "afford":
![image](https://user-images.githubusercontent.com/2634759/147421552-6c6159b2-1d7a-4eb0-89d5-0d9c5c566cbc.png)

And here's the twig barge in my city:
![image](https://user-images.githubusercontent.com/2634759/147421561-cc2de981-c09c-4593-964e-781ba3aff08d.png)

Did y'all run into issues when doing this? If so, do you have the links you used for the game or a use case that I could test out? Thanks!

**Comment by philipstephen2000** [comment]
I played this yesterday and whilst the game recognised the ability of the judge by offering various cards to play, when it came to initiating the card use the error message came up " You want to spend 3 berries and you only have 2 berries". 
You should be able to choose which resource you want to substitute as in the board game there are many examples where this has been well implemented.
Game reference is everdell.vercel.app/game/7g6iqLRFKqCBA7pgjWPzvv?playerSecret=3NBCD7ZCeaA2RKYxUZAWez

**Comment by philipstephen2000** [comment]
Sorry looked at your example again and I wonder if it works when there is only one possible substitute but flounders when it needs to make a choice but as previously stated we need to be able to choose the substitute from available resources.

**Comment by elynnlee** [comment]
Yep -- if you only had 2 berries and needed to pay 3, you would need to specify that you're going to pay, say, 2 berries and 1 resin. When you tried to play the card, did you specify the resource you were substituting in place of the berry?

I see a couple of examples in the error logs:
- Queen: Error says "Can't spend 5 BERRY, you have: 3" --> Judge wouldn't have helped here, and you would have needed to use another payment method to play this card (such as occupying the Palace or Evertree, or using the Innkeeper). If the Palace was in your city, you would see a checkbox like this one: 
![image](https://user-images.githubusercontent.com/2634759/147838370-5254dd4f-2320-47f4-bdc3-2b2aae192d44.png)
- Palace: Error says "Can't spend 3 PEBBLE, you have: 2" --> The player attempted to play this card w/ the base cost (2 twigs, 3 resin, and 3 pebbles), but presumably they didn't have 3 pebbles. To play this card using the Judge, the player would need to input something like 3 TWIG, 3 RESIN, and 2 PEBBLE (ie, substitute one of the PEBBLE for one TWIG) using the input box.

Let me know if you'd tried something like this and it didn't work though! Definitely good feedback about the error message and the payment interface when using the Judge.

**Comment by elynnlee** [comment]
Hi @hannahcin and @philipstephen2000 !! Let us know if you are still encountering this issue after trying what I mentioned above. If it's working as intended, I'll switch this over to a "feature request" to track the feedback that it's not clear how to use the Judge to substitute resources.
