### ISSUE TITLE
Monk giving 2 berries when opponents ended game issue

### ISSUE THREAD

**Issue by kentemere** [ymichael/everdell#66]
Just having a 2 player game alone.
Player 2 ended the game.
Player 1 activated monk, but when I should select the player to give 2 berries, I have no options, so I can't continue the game.

**To Reproduce**
1. End the game with all players except one.
2. Make the last player play monk
3. See error

**Expected behavior**
You give one player who ended the game 2 berries, or you can't use the Monk card if there are no player left.
Actually I don't know how official rules applies here.

**Screenshots**
![1](https://user-images.githubusercontent.com/101206736/157291165-be0a0729-eebd-463d-865c-e0ace45fcafb.png)
![2](https://user-images.githubusercontent.com/101206736/157291174-6da5eb4b-b8ed-4bd6-bec5-223783bf7285.png)

**Browser / Device Info (if relevant):**

- Windows 10
- Google Chrome 98.0.4758.102 (official Build) (64 bit)
- Version [e.g. 22]:

**Comment by elynnlee** [comment]
@kentemere do you mind providing your game link (or the spectator link for your game)? Happy to take a look into this.

**Comment by kentemere** [comment]
Sure!
https://everdell.vercel.app/game/tbdZEfB4RuC5zLWYfcauej

**Comment by elynnlee** [comment]
Hi!! Thanks for waiting -- I figured out the issue and have pushed a fix. The change will deploy soon. Sorry for the inconvenience this caused, and thank you for reporting the issue!
