### ISSUE TITLE
Game stuck on messenger action

### ISSUE THREAD

**Issue by mwojterski** [ymichael/everdell#67]
The game is stuck, no card may be selected to share a space with, here's a link:
https://everdell.vercel.app/game/x1CvFS5kSJdMJGG4tE2FTg?playerSecret=qV5vKRN7AMQdmm3jJVaR5z

**Comment by elynnlee** [comment]
This is the same issue: https://github.com/ymichael/everdell/issues/62

**Comment by elynnlee** [comment]
https://github.com/ymichael/everdell/issues/62 is the same issue -- will close that task + keep this one as the main tracking instance
