### ISSUE TITLE
[soft-lock] Monastery action should give any resource, not just berries

### ISSUE THREAD

**Issue by caeleel** [ymichael/everdell#70]
When using the monastery action, the game allows you to perform it even if you have < 2 berries.

The action is supposed to let you give any type of resource, but it seems like the implementation forces you to give berries.

If you have less than 2 berries at this point, the game becomes soft-locked.

**To Reproduce**
1. Have less than 2 berries
2. Use monastery action
3. Game is soft-locked

**Expected behavior**
You should be able to give any type of resource, not just berries.
The game should not be soft-locked.

**Comment by elynnlee** [comment]
@caeleel do you mind sharing the link where this happened? The Monastery should allow you to give 2 resources (any of them, not just berries), and we explicitly check that you have at least 2 resources when checking if this is an eligible location to visit.

I'd also love to look at what the "state" looks like (eg, if you got an error or what the input looks like). Thank you!

**Comment by elynnlee** [comment]
Thanks for reporting this! We've deployed a fix, but unfortunately your game is going to stay locked because of the way the game inputs work :(

**Comment by caeleel** [comment]
haha no worries we weren't gonna go back to it after all that time anyway. Thanks for the speedy fix!
