### ISSUE TITLE
Baker should give max of 6 bonus points, not 3.

### ISSUE THREAD

**Issue by caeleel** [ymichael/everdell#72]
Merry christmas!

Game link to example: https://everdell.vercel.app/game/v2:eU1QFxUz76ppxcM6AqhQBf?playerSecret=eHWDhBPXVvbgyxPGG8immg

Baker says up to a max of 3, but this is 3 berries, not 3 points. Game manual:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/12506837/209461696-cced7741-d9d4-4853-9f27-0ea26b3db841.png">

**Comment by elynnlee** [comment]
Thanks for reporting this! Fix is out + deployed :)
