### ISSUE TITLE
"Points" label under WIFE card does not update when paired with Husband

### ISSUE THREAD

**Issue by Jnevin10** [ymichael/everdell#73]
When players have both a wife and a husband in their hand, the wife remains worth only 2 points. It should be worth 5 (base value of 2 plus the 3 bonus points for being paired with the husband)

**Comment by elynnlee** [comment]
Hi! Thanks for reporting this. This is an issue with the UI, but the points will be awarded correctly. We'll look into adjusting the "Points" label shown underneath the card. Sorry for the confusion!

**Comment by Jnevin10** [comment]
Oh, you’re totally right, thanks so much for letting me know, I hadn’t
realized that!!!

Also, while we’re here, let me also say thank you so much for making this,
I play in person all the time, but some of my best friends who I love to
play with are all over the world and it is so fun for us to get to be able
to play together. You are very kind, and we are all very grateful!
