### ISSUE TITLE
Newleaf expansion visitor action incorrect

### ISSUE THREAD

**Issue by marialed** [ymichael/everdell#75]
**Describe the bug**
According to the rules, when you pick up a Visitor in the Newleaf expansion, you then pick up a Train Car tile.
The game does not offer to pick a Train Car tile, but instead ends your turn after you discard and then pick a Visitor.

**To Reproduce**
Place worker on Station/"Discard 1 Visitor at the station, then gain 1 visitor and 1 train car tile' action.
Discard a Visitor
Select a Visitor
Submit > you only get the Visitor

If not shown, try as the first player in a new game. That's where it was observed.

**Expected behavior**
Place worker on Station/"Discard 1 Visitor at the station, then gain 1 visitor and 1 train car tile' action.
Discard a Visitor
Select a Visitor
Submit > select Train Car tile option shown

**Browser / Device Info (if relevant):**

- Mac
- Chrome
- v114.0.5735.198

**Comment by elynnlee** [comment]
Fix has been deployed -- thanks again!
